name: Build Android Push
on: [push]
jobs:
  build-debug-apk:
    name: Assemble
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 1.8
        
      - name: Gradle Assemble Debug
        run: ./gradlew assembleDebug
      
        
  
