name: Build Android Push
on: [push]
jobs:
  build-debug:
    name: Checkout Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 8.0.382+5
          distribution: zulu
          
      - name: Assemble Debug
        run: |
          ls -a
          ./gradlew assembleDebug
      
